## code to prepare `method_summary_table` dataset goes here
library(tidyverse)

svg_assets <- tibble(fn = c(
  aggreCAT:::B_ic, 
  aggreCAT:::EngWAgg, 
  aggreCAT:::ReasonWAgg, 
  aggreCAT:::ReasonWAgg2, 
  aggreCAT:::three_point_all_rounds, 
  aggreCAT:::three_point_bounds_all_claims, 
  aggreCAT:::three_point), 
  asset_name = c(
    "B_ic", 
    "EngWAgg", 
    "ReasonWAgg", 
    "ReasonWAgg2", 
    "three_point_all_rounds", 
    "three_point_bounds_all_claims", 
    "three_point")
) # Because local_image() wasn't happy when called inside Rmarkdown no matter what I did with filepaths

method_summary_table <- tibble::tribble( #extracted from csv with datapasta::
  ~aggregator_function,                                                                                                                                                      ~aggregator_fun_desc,              ~type,                                                                                                                                                            ~type_desc,    ~supp_data_requirements,                                                             ~weighting_fn, ~number_rounds,                                                                                                                       ~elicitation_method,                                                   ~judgement_data_sources_eqns, ~judgement_data_sources_svg_file,
  "AverageWAgg()",                                                                                                                                                 "Averaged best estimates",           "ArMean",                                                                                                                               "Arithmetic mean of the best estimates",                         NA,                                     "NA - Estimates are equally weighted",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "AverageWAgg()",                                                                                                                                                 "Averaged best estimates",           "Median",                                                                                                                                        "Median of the best estimates",                         NA,                                     "NA - Estimates are equally weighted",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "AverageWAgg()",                                                                                                                                                 "Averaged best estimates",          "GeoMean",                                                                                                                                "Geometric mean of the best estimates",                         NA,                                     "NA - Estimates are equally weighted",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "AverageWAgg()",                                                                                                                                                 "Averaged best estimates",         "LOArMean",                                                                                                          "Arithmetic mean of the log odds transformed best estimates",                         NA,             "NA - Estimates are equally weighted prior to transformation",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "AverageWAgg()",                                                                                                                                                 "Averaged best estimates",     "ProbitArMean",                                                                                                            "Arithmetic mean of the probit transformed best estimates",                         NA,             "NA - Estimates are equally weighted prior to transformation",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "LinearWAgg()",                                                                                                                                        "Linearly-weighted best estimates",    "DistLimitWAgg",               "Weighted by the distance of the best estimate from the closest certainty limit. Best-estimates closest to certainty limits are more strongly weighted",                         NA,                                                   "Calculated internally",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "LinearWAgg()",                                                                                                                                        "Linearly-weighted best estimates",         "GranWAgg",                                                                                                                       "Weighted by the granularity of best estimates",                         NA,                                                   "Calculated internally",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "LinearWAgg()",                                                                                                                                        "Linearly-weighted best estimates",        "Judgement",                                                                                                            "Weighted by user-supplied weights at the judgement level",                      "???",                                                                     "???",          "???",                                                                                                                                     "???",                                                                          "???",                               NA,
  "LinearWAgg()",                                                                                                                                        "Linearly-weighted best estimates",      "Participant",                                                                                                          "Weighted by user-supplied weights at the participant level",                      "???",                                                                     "???",          "???",                                                                                                                                     "???",                                                                          "???",                               NA,
  "LinearWAgg()",                                                                                                                                        "Linearly-weighted best estimates",          "OutWAgg",                                                                                                                                         "Outliers are down-weighted.",                         NA,                                                      "`weight_outlier()`",          "???",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "IntervalWAgg()",                                                                                            "Linearly-weighted best estimates, with weights influenced by interval widths",          "IntWAgg",                                                                                                                                          "Weighted by interval width",                         NA,                                                     "`weight_interval()`",            "1",                                                                                                                             "Three-point",                                            "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}$",                    "three-point",
  "IntervalWAgg()",                                                                                            "Linearly-weighted best estimates, with weights influenced by interval widths",       "IndIntWAgg",                                             "Weighted by the re-scaled interval width (interval width relative to largest interval width provided by individual $i$.",                         NA,                                               "`weight_nIndivInterval()`",            "1",                                                                                                                             "Three-point",                      "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}, {U}_{i,d}, {L}_{i,d}$",  "three-point_bounds-all-claims",
  "IntervalWAgg()",                                                                                            "Linearly-weighted best estimates, with weights influenced by interval widths",         "AsymWAgg",                                                                                                                                   "Weighted by asymetry of intervals",                         NA,                              "`weight_asym()`, `weight_nIndivInterval()`",            "1",                                                                                                                             "Three-point",                                            "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}$",                    "three-point",
  "IntervalWAgg()",                                                                                            "Linearly-weighted best estimates, with weights influenced by interval widths",   "IndIntAsymWAgg",                                                                                                         "Weighted by individuals' interval widths and their asymetry",                         NA,                              "`weight_asym()`, `weight_nIndivInterval()`",            "1",                                                                                                                             "Three-point",                      "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}, {U}_{i,d}, {L}_{i,d}$",  "three-point_bounds-all-claims",
  "IntervalWAgg()",                                                                                            "Linearly-weighted best estimates, with weights influenced by interval widths",    "VarIndIntWAgg",                                                                                          "Weighted by the variation in individuals' interval widths across estimates",                         NA,                                             "`weight_varIndivInterval()`",            "1",                                                                                                                             "Three-point",                      "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}, {U}_{i,d}, {L}_{i,d}$",  "three-point_bounds-all-claims",
  "IntervalWAgg()",                                                                                            "Linearly-weighted best estimates, with weights influenced by interval widths",    "KitchWinkWAgg",  "Weighted by everything but the kitchen sink - rewards narrow and assymetric intervals as well as the variability of individuals' interval widths across estimates.",                         NA, "`weight_asym()`, `weight_nIndivInterval()`, `weight_varIndivInterval()`",            "1",                                                                                                                             "Three-point",                      "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}, {U}_{i,d}, {L}_{i,d}$",  "three-point_bounds-all-claims",
  "ShiftingWAgg()",                                                                                                                 "Weighted by judgemetns that shift most after discussion",        "ShiftWAgg",                                                                           "Accounts for shifts in individuals' best-estimates, upper and lower bounds between rounds",                         NA,                                                   "Calculated internally",            "2",                   "IDEA protocol or other structured protocol that generates multiple rounds of judgements using three-point elicitation",     "${B1}_{i,c}, {U1}_{i,c}, {L1}_{i,c}, {B1}_{i,c}, {U1}_{i,c}, {L1}_{i,c}$",         "three-point_all-rounds",
  "ShiftingWAgg()",                                                                                                                 "Weighted by judgemetns that shift most after discussion",    "BestShiftWAgg",                                                                                                                   "Weights constructed from shifts in best-estimates",                         NA,                                                   "Calculated internally",            "2",                       "IDEA protocol or other structured protocol that generates multiple rounds of judgements of single point-estimates",                                                                  "${B}_{i,c}$",                           "B_ic",
  "ShiftingWAgg()",                                                                                                                 "Weighted by judgemetns that shift most after discussion",     "IntShiftWAgg",                                                                                                                  "Weights constructed from shifts in interval widths",                         NA,                                                   "Calculated internally",            "2",                   "IDEA protocol or other structured protocol that generates multiple rounds of judgements using three-point elicitation",                                            "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}$",                    "three-point",
  "ShiftingWAgg()",                                                                                                                 "Weighted by judgemetns that shift most after discussion",    "DistShiftWAgg",                                                                                               "Weights constructed from degree of extrimisation shift between rounds",                         NA,                                                   "Calculated internally",            "2",                       "IDEA protocol or other structured protocol that generates multiple rounds of judgements of single point-estimates",                                                                  "${B}_{i,c}$",                           "B_ic",
  "ShiftingWAgg()",                                                                                                                 "Weighted by judgemetns that shift most after discussion", "DistIntShiftWAgg",                                                               "Weights constructed by degree of interval narrowing and shift towards certainty bounds between rounds",                         NA,                                                   "Calculated internally",            "2",                   "IDEA protocol or other structured protocol that generates multiple rounds of judgements using three-point elicitation",                                            "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}$",                    "three-point",
  "ReasoningWAgg()",                                                                            "Linearly-weighted best estimates, with weights constructed from supplementary reasoning data",       "ReasonWAgg",                                                     "Weighted by the breadth of reasoning (number of supplied reasons) provided to support the individuals' estimate",   "`data_supp_ReasonWAgg`",                                                       "`weight_reason()`",            "1", "IDEA protocol or other structured protocol to elicit reasoning, but only sinle round (round 2) of data used in aggregation calculation.",                                        "${B}_{i,c}$, $w${\\_}${reason}_{i,c}$",                     "ReasonWAgg",
  "ReasoningWAgg()",                                                                            "Linearly-weighted best estimates, with weights constructed from supplementary reasoning data",      "ReasonWAgg2",                             "Weighted by the breadth of reasoning provided to support the individuals' estimate, rescaled  by breadth of reasoning across all claims",   "`data_supp_ReasonWAgg`",                                                      "`weight_reason2()`",            "1", "IDEA protocol or other structured protocol to elicit reasoning, but only sinle round (round 2) of data used in aggregation calculation.", "${B}_{i,c}, w{\\_}{reason}_{i,c}, {U}_{i,d}, {L}_{i,d}, w{\\_}{reason}_{i,c}",                    "ReasonWAgg2",
  "ExtremisationWAgg()",                                                "Takes the average of best-estimates and transforms it using the cumulative distribution function of a beta distribution.",       "BetaArMean",                                                                                                              "Beta-transformed arithmetic mean of the best-estimates",                         NA,                                     "NA - Estimates are equally weighted",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "ExtremisationWAgg()",                                                "Takes the average of best-estimates and transforms it using the cumulative distribution function of a beta distribution.",      "BetaArMean2",                                             "Beta-transformed arithmetic mean of the best-estimates, but only to confidence scores outside a specified middle range.",                         NA,                                     "NA - Estimates are equally weighted",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic",
  "DistributionWAgg()", "Calculates the arithmetic mean of distributions created from expert judgements. The aggregate is the median of the average distribution fitted to individual estimates.",    "DistribArMean",                                                                                 "Applies a non-parametric distribution evenly across upper, lower and best-estimates",                         NA,                                     "NA - Estimates are equally weighted",            "1",                                                                                                                             "Three-point",                                            "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}$",                    "three-point",
  "DistributionWAgg()", "Calculates the arithmetic mean of distributions created from expert judgements. The aggregate is the median of the average distribution fitted to individual estimates.", "TriDistribArMean",                                                                                            "Applies a triangular distribution to the upper, lower and best-estimates",                         NA,                                     "NA - Estimates are equally weighted",            "1",                                                                                                                             "Three-point",                                            "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}$",                    "three-point",
  "BayesianWAgg()",                                                                              "Bayesian aggregation methods with either uninformative or informative prior distributions.",        "BayTriVar",                                                                                                                                 "Bayesian tripple variability method",                         NA,                                     "NA - Estimates are equally weighted",            "1",                                                                                                                             "Three-point",                                            "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}$",                    "three-point",
  "BayesianWAgg()",                                                                              "Bayesian aggregation methods with either uninformative or informative prior distributions.",     "BayPRIORsAgg",                                                "As per `BayTriVar` but with priors derived from external predictive models, updated with individuals' best-estimates", "`data_supp_BayPRIORsAgg`",                                     "NA - Estimates are equally weighted",            "1",                                                                                                                             "Three-point",                                            "${B}_{i,c}, {U}_{i,c}, {L}_{i,c}$",                    "three-point",
  "???",                                                                                                                                                                     "???",         "?EngWAgg",                                                                                       "Weighted by the level of engagement as measured by the individuals' verbosity",    "`data_justifications`",                                                   "Calculated internally",            "2",                                                                                                                            "Single-Point",                                          "${B}_{i,c}$, $w$ {\\_}${Eng}_{i,c}$",                        "EngWAgg",
  "???",                                                                                                                                                                     "???",        "?CompWAgg",                                                                              "Weighted by the level of self rated comprehension of the claim the individuals' report",                         NA,                                                   "Calculated internally",            "1",                                                                                                                            "Single-Point",                                                                  "${B}_{i,c}$",                           "B_ic"
) %>% 
  dplyr::left_join(svg_assets, by = c( "judgement_data_sources_svg_file"= "asset_name" ))


usethis::use_data(method_summary_table, overwrite = TRUE)
