# # Generated by pointblank
#
# tbl <- weight_experience(data_ratings, round_for_agg = "round_1")
#
# test_that("column `paper_id` exists", {
#
#   expect_col_exists(
#     tbl,
#     columns = vars(paper_id),
#     threshold = 1
#   )
# })
#
# test_that("column `user_name` exists", {
#
#   expect_col_exists(
#     tbl,
#     columns = vars(user_name),
#     threshold = 1
#   )
# })
#
# test_that("column `weight` exists", {
#
#   expect_col_exists(
#     tbl,
#     columns = vars(weight),
#     threshold = 1
#   )
# })
#
# test_that("column `weight` is of type: numeric", {
#
#   expect_col_is_numeric(
#     tbl,
#     columns = vars(weight),
#     threshold = 1
#   )
# })
#
# test_that("column `paper_id` is of type: character", {
#
#   expect_col_is_character(
#     tbl,
#     columns = vars(paper_id),
#     threshold = 1
#   )
# })
#
# test_that("column `user_name` is of type: character", {
#
#   expect_col_is_character(
#     tbl,
#     columns = vars(user_name),
#     threshold = 1
#   )
# })
